### DISCUSSION TITLE
Docstring at multilevel inheritance

### DISCUSSION THREAD

**Discussion by jannifri** [mkdocstrings/python#125] [Q&A] [answered]
Hello,
I have a question/problem:

When I have a multilevel inheritance architecture, is there a way to show the docstring of the “base”-class?
Currently, it seems that only the docstring of the inherited class of the first level will be considered.

Here is an example (example.py):

```
from abc import ABC

class MyIface(ABC):
    """This is my iface."""

    def __init__(self):
        """Init MyIface."""
        pass

    def func(self):
        """This is docstring of func_iface."""
        pass

class A(MyIface):
    """This is A."""

    def __init__(self):
        """Init Base."""
        pass

    def func(self):
        pass

    def func_A(self):
        """This is docstring of func_A."""
        pass

class B(A):
    """This is B."""

    def __init__(self):
        """Init Base."""
        pass
```

I want to render the docs of “class B”

_In markdown file:_ 
`::: example.B`

_settings in .yml-file:_
```
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          docstring_style: google
          docstring_section_style: table
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_if_no_docstring: true
          show_docstring_description: True
          show_bases: False
          show_source: False
          show_root_toc_entry: false
          inherited_members: true
          heading_level: 3
```

Result:
![grafik](https://github.com/mkdocstrings/python/assets/61515349/9e534438-9f5f-4c8d-b9e8-1254a2eda49c)

The docstring of “func” is not shown, although a docstring exists in the base-class "MyIface" .

Are there any ways to solve this problem?
Thank you for your help.
