### DISCUSSION TITLE
Imports in __init__.py

### DISCUSSION THREAD

**Discussion by viktor40** [mkdocstrings/python#188] [Q&A] [answered]
Hi, I'm using material for mkdocs together with mkdocstrings to create documentation for a python library. Because there are many subfolders in this library, some imports are added in `__init__.py` files to allow for shorter imports.

Example:
Take a module with the following structure `package.submodule1.submodule2.example_class.ExampleClass`
There is an `__init__.py` file in the package directory with the following import in it:
`from .submodule1.submodule2.class import ExampleClass`

by doing this, the user can import `ExampleClass` by doing:
`from package import ExampleClass`
which is much shorter.

How can I document this option when using mkdocstrings. For example, I am using the `show_root_full_path: true` option in the `mkdocs.yml` file. So the generated documentation has the full import in it. I would like the users to know about the shortened imports from the documentation so I would like to either show only the shortened import or both the full import and shortened import. Is this possible in any way?

**Comment by pawamoy** [comment, marked as answer]
Hello!

It is not clear exactly how you inject documentation into your pages, but you can:

- document this in your class docstring
- make your alias `package.ExampleClass` public (by listing it in `__all__`), and mkdocstrings-python will render it when injecting docs for `package`. its full path will show as `package.ExampleClass`

Does that help?

**Reply by viktor40** [reply]
Thanks for the quick response.

My `__init__.py` file in `package` now looks like this:
```
from .submodule1.submodule2.class import ExampleClass

__all__ = [
    ExampleClass,
]
```

However, when going to the documentation for `package`, or for `ExampleClass`, the alias is not visible.

As extra information, I used the [Automatic code reference pages](https://mkdocstrings.github.io/recipes/) recipe to generate the markdown files for my API reference (although I don't think this should matter).

Below, you can also find my mkdocstring configuration in `mkdocs.yml` (if this matters).
```
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            annotations_path: brief
            show_source: false
            show_signature: true
            show_root_toc_entry: false
            show_bases: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_symbol_type_heading: true
```
