### DISCUSSION TITLE
Automatic references to docs of built-in members

### DISCUSSION THREAD

**Discussion by mbraakhekke** [mkdocstrings/python#228] [Q&A] [answered]
How do I get `mkdocstrings-python` to create links to docs of built-in members (e.g [`str`](https://docs.python.org/3/library/stdtypes.html#str)) for signatures and attributes? I tried a bunch of options but I can't get it to work.

**Comment by pawamoy** [comment, marked as answer]
You have to load the Python docs' objects inventory:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
```
