### DISCUSSION TITLE
How to autodoc a patched module

### DISCUSSION THREAD

**Discussion by davlee1972** [mkdocstrings/python#260] [Q&A] [answered]
I'm trying to document some patches & bug fixes made to existing packages, but griffe isn't finding the patched items.

Any suggestions on how to get this to work?

Here is a example:

string_mod.py file which adds a hello attribute as a patch
```python
import string
string.hello = "hello"
```

in strings_documentation.md
```markdown
::: string
    options:
      members:
        - hello
```

in mkdocs.yml load string_mod.py as a extension
```yaml
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            extensions:
              - string_mod

nav: strings_documentation.md
```
