### DISCUSSION TITLE
docstring style for toc_label not working as expected

### DISCUSSION THREAD

**Discussion by ccmao1130** [mkdocstrings/python#267] [Q&A] [answered]
I'm trying to do this as stated in the [docs](https://mkdocstrings.github.io/python/usage/configuration/headings/#toc_label):
```
::: path.to.module
    options:
        heading: my fancy module
        toc_label: my fancy module
```
however, only `heading` is updated to "My fancy module" but not `toc_label`
<img width="597" alt="image" src="https://github.com/user-attachments/assets/9b74d304-a3a3-4a33-94f0-86adc67a2942" />
`query` under JSON in the nav should have been configed as "My fancy module" as well

am i using the wrong heading option maybe?
