### ISSUE TITLE
bug: merge_init_into_class not working

### ISSUE THREAD

**Issue by mRcSchwering** [mkdocstrings/python#118]
### Description of the bug

I am trying to show use [merge_init_into_class](https://mkdocstrings.github.io/python/usage/configuration/docstrings/#merge_init_into_class).
I have set [show_if_no_docstring](https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_if_no_docstring) to `true`,
[filters](https://mkdocstrings.github.io/python/usage/configuration/members/#filters) to `["!^_", "^__init__$"]`,
[show_signature](https://mkdocstrings.github.io/python/usage/configuration/signatures/#show_signature) to `true`.

Methods are shown with their signatures and docstrings.
However classes are shown without signature and only with their docstring.
Class inits are shown with signature and without docstring (they don't have one).
Classes are shown with their docstring but without signature.

### To Reproduce

_python/amodule.py_

```python
class A:
    """
    This is class A
    """

    def __init__(self, a: str):
        self.a = a
```

_reference.md_

```markdown
::: amodule
```

_mkdocs.yml_

```yaml
site_name: MySite
theme: readthedocs

nav:
  - "reference.md"

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [python]
          options:
            heading_level: 3
            merge_init_into_class: true
            show_bases: false
            show_root_toc_entry: false
            show_source: false
            show_object_full_path: false
            members_order: source
            show_signature: true
            show_if_no_docstring: true
            filters: ["!^_", "^__init__$"]
```

serve with

```bash
mkdocs serve
```

### Expected behavior

I would like to see the class name with the init signature and the class docstring.
So from the example above, I would like to see something like:

```html
<h3>A(a)</h3>
This is class A
```

But currently it shows something like this:

```html
<h3>A</h3>
This is class A

<h3>__init__(a)</h3>
```

### Environment information

`python -m mkdocstrings_handlers.python.debug`
fails with `No module named mkdocstrings_handlers.python.debug`.

I have installed:

```
mkdocs==1.5.3
mkdocstrings[python]==0.24.0
```
