### ISSUE TITLE
feature: hide toc entry for members

### ISSUE THREAD

**Issue by samvanstroud** [mkdocstrings/python#141]
It would be great to have the option not to add members to the table of contents.

It should be possible to maintain similar formatting using heading tags as mentioned here
https://github.com/squidfunk/mkdocs-material/discussions/2532#discussioncomment-588025

**Comment by pawamoy** [comment]
Thanks for the request. In the current state of the code (and its dependencies), it is difficult to achieve this. But it's doable with CSS, as mentioned in the link you posted. I'll add a documentation label to this issue to add a CSS example in the docs :slightly_smiling_face:

**Comment by pawamoy** [comment]
Copying a snippet for our Gitter channel:

```css
/* Hide all ToC entries for members of a class. */
li.md-nav__item > a[href*="path.to.class."] {
  display: none;
}

/* Except for specific members. */
li.md-nav__item > a[href="#path.to.class.specific_member"] {
  display: inline-block;
}
```
