### ISSUE TITLE
bug: missing types for attributes documented in `__init__` method

### ISSUE THREAD

**Issue by CunliangGeng** [mkdocstrings/python#144]
### Description of the bug

If attributes are documented in the `__init__` method (see class below), their types are missing after rendering (see the screenshot).

```
class MolecularFamily:
    def __init__(self, family_id: str):
        """Class to model molecular family.

        Args:
            family_id: Unique id for the molecular family.

        Attributes:
            family_id: Unique id for the molecular family.
            spectra_ids: Set of spectrum ids in the molecular family.
        """
        self.family_id: str = family_id
        self.spectra_ids: set[str] = set()
        self._spectra: set[Spectrum] = set()
        self._strains: StrainCollection = StrainCollection()
```

screenshot
![image](https://github.com/mkdocstrings/python/assets/9798985/54efd1a6-496f-4c69-b2f3-e5df4045152a)

### To Reproduce

```
WRITE MRE / INSTRUCTIONS HERE
```

### Full traceback

<details><summary>Full traceback</summary>

```python
PASTE TRACEBACK HERE
```

</details>

### Expected behavior
Not matter where attributes are documented (module level, class level or `__init__` method), their types should be extracted and rendered properly.

### Environment information

```bash
python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
```

- __System__: macOS-14.4.1-arm64-arm-64bit
- __Python__: cpython 3.9.18
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.5.3
  - `mkdocstrings` v0.24.1
  - `mkdocstrings-python` v1.9.0
  - `griffe` v0.42.0

### Additional context

mkdocs.yml
```
plugins
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          filters: ["!^_"]
          merge_init_into_class: true
          show_if_no_docstring: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          signature_crossrefs: true
          separate_signature: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
```
