### ISSUE TITLE
bug: `show_symbol_type_toc` not working with newest version of Python handler / material theme

### ISSUE THREAD

**Issue by femtomc** [mkdocstrings/python#158]
Hi!

### Description of the bug
I'm using the newest insider's edition of `mkdocstrings-python`, and I'm attempting to use:

```
plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      handlers:
        python:
          options:
            show_symbol_type_toc: true
```

in my documentation (with an admittedly old insider's edition of `mkdocs-material`). However, the symbols are not rendering in the side ToC.

### Expected behavior
I expect the symbol types to show up next to the entries in the side ToC.

### Environment information

Here's my exact versioning:

```
mkdocs                                    1.5.3
mkdocs-autorefs                           1.0.1
mkdocs-git-authors-plugin                 0.7.2
mkdocs-git-committers-plugin-2            1.2.0
mkdocs-git-revision-date-localized-plugin 1.2.5
mkdocs-material                           9.5.4+insiders.4.49.2
mkdocs-material-extensions                1.3.1
mkdocstrings                              0.25.0
mkdocstrings-python                       1.10.0.1.8.2.dev19+g995e505
```

### Additional context

Now, I do have some errors in my documentation -- but all other `mkdocstrings-python` options work correctly (e.g. `show_symbol_type_heading` works fine) and I can switch them on and off and build my documentation without issue.

**Comment by pawamoy** [comment]
Try to upgrade your mkdocs-material dependency :slightly_smiling_face:

**Comment by femtomc** [comment]
haha, of course! thank you, sorry for the time waste

**Comment by pawamoy** [comment]
No problem! Thanks for trying this so quickly :smile:

**Comment by femtomc** [comment]
@pawamoy Unfortunately, still encountering this with the following (up-to-date) dependencies:

```
mkdocs-material                           9.5.21+insiders.4.53.8
mkdocs-material-extensions                1.3.1
mkdocstrings                              0.25.0
mkdocstrings-python                       0.1.dev395+g995e505
```

Here's my full plugin config:
```
plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      handlers:
        python:
          options:
            show_symbol_type_toc: true
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            parameter_headings: true
            separate_signature: true
            signature_crossrefs: true
            show_signature_annotations: true
```
