### ISSUE TITLE
bug: Docstring Style Local Override Does Not Work

### ISSUE THREAD

**Issue by triley13** [mkdocstrings/python#183]
### Description of the bug
Local override `docstring_style` for global configuration doesn't work.

### To Reproduce

Declare in mkdocs.yaml:

```
plugins:
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
```
-->

Inside `file.md` 
```
::: path.to.module
    options:
      docstring_style: sphinx
```

### Full traceback

<details><summary>Full traceback</summary>

```python
N/A
```

</details>

### Expected behavior

Override the default `google` style with the `sphinx` style for that one module.

### Environment information

```bash
- __System__: Windows-10-10.0.19045-SP0
- __Python__: cpython 3.10.11
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.0
  - `mkdocstrings` v0.26.0
  - `mkdocstrings-python` v1.10.5
  - `griffe` v0.47.0
```

### Additional context

I am using `path: ` to load the module and I'm using `mkdocs-monorepo-plugin`.
