### ISSUE TITLE
feature: Manually specify external docs url for  docs without objects.inv

### ISSUE THREAD

**Issue by ItsDrike** [mkdocstrings/python#198]
### Is your feature request related to a problem? Please describe.
Some projects use custom documentation that doesn't generate the `objects.inv` file. For these projects, cross-linking to their docs is currently not really possible.

### Describe the solution you'd like
It would be nice if it was possible to specify some concrete object -> url mappings right from the config e.g.:

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - url: https://docs.python.org/3.13/objects.inv
              domains: [std, py]
            - https://typing-extensions.readthedocs.io/en/latest/objects.inv
            # Proposed new section:
            - objects:
                - httpx.AsyncClient: https://www.python-httpx.org/api/#asyncclient
                - httpx.Client: https://www.python-httpx.org/api/#client
```

### Describe alternatives you've considered
It would probably be possible to write the `objects.inv` file for the docs of the external project manually and then host is somewhere for mkdocs to pull it. However, the `objects.inv` format isn't that common and I'm not sure how easy would generating it like this be. The content of this file seems to be compressed, which makes writing it by hand impossible.
