### ISSUE TITLE
bug: properties vs attributes in classes

### ISSUE THREAD

**Issue by mbraakhekke** [mkdocstrings/python#223]
### Description of the bug
Not sure if this is a bug or intentional but I'm a bit confused by the difference between instance/class attributes and properties w.r.t. the summary at the top of the class documentation.  Below a MRE.

### To Reproduce
Project structure:
```
📁 root/
├── 📁 docs/
     └──  index.md
│   
└── 📁 src/
     └──  tmp.py
│
└──  mkdocs.yml   
```

`src/tmp.py`:
```python
class Foo:
    """Foo class.

    Attributes:
        instance_attr: my instance attribute
    """

    instance_attr: str

    @property
    def property_attr(self) -> int:
        """My property attribute"""
        return 1
```

`docs/index.md`:
```markdown
::: src.tmp
```

`mkdocs.yml`:
```yaml
site_name: foo

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: src
        options:
          summary:
            attributes: true
          show_docstring_attributes: true
```

The configuration above results in two "Attributes" sections; one for the property and one for the instance attribute, which is not really desirable:

![image](https://github.com/user-attachments/assets/5d6c9154-e7ff-4fe3-87ee-be7fab49b6c6)

If I switch off the summary generation for attributes, i.e. `attributes: false` in `mkdocs.yml`, I get a single "Attributes" section with only the instance attribute:

![image](https://github.com/user-attachments/assets/1d1b5a0f-047c-4efa-ae5d-31ba9d6d7b8a)

If I set `show_docstring_attributes` to `false` in `mkdocs.yml` I also get a single "Attributes" section but then with only the property:

![image](https://github.com/user-attachments/assets/fffe6a67-cc46-4d83-8428-22b7da28de37)

Is there a way to get a single "Attributes" section with both the properties and the instance/class attributes?
