### ISSUE TITLE
bug: Attributes not inherited when using `inherited_members = True`

### ISSUE THREAD

**Issue by toby-coleman** [mkdocstrings/python#245]
### Description of the bug
I'm documenting some code containing various Pydantic models that inherit from each other, and would like attributes to be inherited in the docs. Methods are inherited while attributes are not.

### To Reproduce

```python
from pydantic import BaseModel

class MyBase(BaseModel):
    """An example.

    Attributes:
        x: An attribute.
    """

    a: str

    def my_method():
        """This is a method."""
        pass

class Another(MyBase):
    """A child class."""

    y: int
```

In `mkdocs.yaml`:
```yaml
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          show_source: False
          show_root_heading: True
          show_symbol_type_toc: True
          show_symbol_type_heading: True
          show_signature_annotations: True
          separate_signature: True
          show_signature_annotations: True
          inherited_members: True
          merge_init_into_class: True
          filters: ["!^_", "^__init__$"]
```

### Expected behavior
Expected both methods and attributes to be inherited in the docs.

### Environment information

```bash
python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
```

```
- __System__: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
- __Python__: cpython 3.9.18 (/home/***/miniconda3/envs/***/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.28.0
  - `mkdocstrings-python` v1.14.5
  - `griffe` v1.5.5
```

### Additional context

![Image](https://github.com/user-attachments/assets/3cdbf9af-c2e8-4dda-9242-095947a56339)
