### ISSUE TITLE
docs: regression, no `python` property in schema

### ISSUE THREAD

**Issue by mattmess1221** [mkdocstrings/python#246]
### Is something unclear, missing or outdated in our documentation?
Schema generation introduced in 5ebeda6fce1b1bc7cb3f5e27a5a90ac394a3de0c is defining all the properties as belonging to root instead of `python`.

### Relevant code snippets

Invalid
```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
```
valid (wrong)
```yaml

plugins:
  - mkdocstrings:
      handlers:
        import:
          - https://docs.python.org/3/objects.inv
```

### Link to the relevant documentation section

https://mkdocstrings.github.io/python/schema.json
https://mkdocstrings.github.io/schema.json
