### ISSUE TITLE
bug: unwrap_annotated not working

### ISSUE THREAD

**Issue by jayqi** [mkdocstrings/python#249]
### Description of the bug

I am using `unwrap_annotated: true` but I still see `Annotated` in my signatures.

![Image](https://github.com/user-attachments/assets/f8b791e8-0199-4d04-aa01-10209c6d62c6)

### Expected behavior

I expect the first two arguments in the signature to render as

```
    editor: Optional[str] = None,
    venue: Venue = Venue.GH,
```

### Environment information

- __System__: macOS-14.7.2-x86_64-i386-64bit
- __Python__: cpython 3.12.7 (/Users/jqi/repos/reprexlite/.venv/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.28.1
  - `mkdocstrings-python` v1.15.0
  - `griffe` v1.5.7

### Additional context

Here is my configuration ([source](https://github.com/jayqi/reprexlite/blob/de89b12ddb183f46bc9d0b47f612e8a40825f79c/docs/mkdocs.yml#L81C1-L107C1)):
```yaml
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../reprexlite]
          options:
            # General
            docstring_style: google
            # Headings options
            heading_level: 2
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_heading: false
            show_category_heading: true
            # Members options
            filters: ["!^_", "^__init__$"]
            # Docstrings options
            show_if_no_docstring: false
            merge_init_into_class: true
            # Signatures/annotation options
            annotations_path: brief
            separate_signature: true
            show_signature_annotations: true
            unwrap_annotated: true
            # Additional options
            show_source: true
```

Here is a link to my class definition: [source](https://github.com/jayqi/reprexlite/blob/de89b12ddb183f46bc9d0b47f612e8a40825f79c/reprexlite/config.py#L48-L100)
