### ISSUE TITLE
bug: summary of modules in `__init__.py` is not linked to modules

### ISSUE THREAD

**Issue by patrick-egenlauf** [mkdocstrings/python#262]
### Description of the bug

I use the `summary: true` option. In my `__init__.py` file I only have a docstring which describes the package. The summary is successfully created and shows all `modules`, but they are not linked. Inside each module the summary shows, e.g. the functions, and the names are clickable and lead directly to the respective function on the same page. I would expect that the module names are linked to the respective page in my documentation.

### To Reproduce

I use `mkdocs-material` and the auto-generation of the API reference mentioned in the [docs of mkdocstrings](https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages). The configuration of `mkdocstrings` in the `mkdocs.yml` file is

```
- mkdocstrings:
    handlers:
      python:
        paths: [src/my_project]
        options:
          docstring_style: google
          docstring_section_style: list
          heading_level: 2
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_bases: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_root_full_path: true
          show_root_heading: false
          show_root_toc_entry: false
          show_root_members_full_path: true
          show_signature_annotations: true
          signature_crossrefs: true
          relative_crossrefs: true
          members_order: source
          summary: true
```

Inside `src/my_project/` I have an `__init__.py` file with a docstring and other files, e.g. `foo.py` and `bar.py`.

### Full traceback

<details><summary>Full traceback</summary>

```python
PASTE TRACEBACK HERE
```

</details>

### Expected behavior

The `module` names should be clickable and link to the page of the respective `module`. In the minimal example above I would expect to be able to click on `foo` and `bar`, which will bring me to the page of the respective `module`.

### Environment information

```bash
python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
- __System__: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
- __Python__: cpython 3.12.5 (/home/usr/Documents/my_project/.venv/bin/python3)
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.28.2
  - `mkdocstrings-python` v1.16.2
  - `griffe` v1.5.7

```

PASTE MARKDOWN OUTPUT HERE
