### ISSUE TITLE
bug: class and function names inside h5 are uppercase / missing .code class for names?

### ISSUE THREAD

**Issue by mzebrak** [mkdocstrings/python#276]
### Description of the bug

It is similar/related to https://github.com/squidfunk/mkdocs-material/issues/7734 which resulted in [this fix](https://github.com/squidfunk/mkdocs-material/commit/b3f1eb27fe4ff3f050a84173b0c998323bb120c1#diff-187ba8c85f1aa9af70a95f5243a13376d102ecdec56b535212db5478a4f00769R149)

The issue is that the text inside h5 headers (class names, function names) is converted to uppercase.

Since there is a fix already in the `mkdocs-material` itself, which disables this `uppercase` formatting inside `h5.code` CSS class, maybe all the class/function names should have the  `.code` class? 

![Image](https://github.com/user-attachments/assets/335ad5a7-6aaa-41ee-978c-786097f4dc8d)

### To Reproduce

Enable the `show_submodules` option and have a nested submodules structure, so `h5` header will be created for class/function.

Like :
1. Declare in mkdocs.yml

```yaml
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_submodules: true
```

2. Define a class like `mypackage.exceptions.account_errors.AccountNotFoundError`

### Expected behavior
The class names (and function names) will be the same as in the python code. (so `AccountNotFoundError` and not `ACCOUNTNOTFOUNDERROR`)

### Environment information

- cpython 3.12.3
- mkdocs 1.6.1
- mkdocstrings-python 1.16.10
- mkdocs-material 9.6.12

### Additional context

I think it is related to: https://github.com/squidfunk/mkdocs-material/issues/1522 and https://github.com/squidfunk/mkdocs-material/issues/7734, which resulted in [this fix](https://github.com/squidfunk/mkdocs-material/commit/b3f1eb27fe4ff3f050a84173b0c998323bb120c1#diff-187ba8c85f1aa9af70a95f5243a13376d102ecdec56b535212db5478a4f00769R149)

The workaround seems to be:

```css
h5 .doc-object-name {
  text-transform: none;
}
```

defined in the `extra.css`
