### ISSUE TITLE
bug: broken `auto_title` in function signatures

### ISSUE THREAD

**Issue by nataziel** [mkdocstrings/python#281]
### Description of the bug
In 1.16.11, if `auto_title` is set in `pymdownx.highlight` the added title is not rendered as part of the signature code block. This also breaks the signature code block highlighting.

### To Reproduce

set the following in mkdocs.yml
``` yml
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      auto_title: true
```

View any generated documentation

### Expected behavior
inside div `language-python doc-signature highlight`, the span containing Python should be class `filename`, not `nf`.

### Environment information

- __System__: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
- __Python__: cpython 3.10.12 (/usr/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings-python` v1.16.10

### Additional context
Pretty sure this is due to this commit: https://github.com/mkdocstrings/python/commit/7f956868f93a766346455fedb296c26787894d5c
The regex `<span class="[a-z]+">` matches `<span class="filename">`. You could use `<span class="[a-z]{1,2}">` instead potentially?
