### ISSUE TITLE
Wrong URL for external package cross-reference

### ISSUE THREAD

**Issue by jaywonchung** [mkdocstrings/python#32]
**Describe the bug**
A cross reference to `torch.utils.data.DataLoader` is rendered with incorrect links.
<img width="1106" alt="Screen Shot 2022-08-04 at 12 29 12 PM" src="https://user-images.githubusercontent.com/29395896/182902757-827a2a83-820b-40e0-bd4c-a8e3e74263f3.png">
Here, `torch` points to https://pytorch.org/docs/1.10.1/data.html#module-torch.utils.data. `data` and `DataLoader` point to correct URLs.

I opened up the `objects.inv` file provided by PyTorch with `Inventory.parse_sphinx` and found that it does not have entries for `torch` and `torch.utils`. In such a case, I think `torch` should not point to anything like how `torch.utils` is not linked to anything.

**To Reproduce**
```python
# test.py
import torch.utils.data

class MyDataLoader(torch.utils.data.DataLoader):
    pass
```
```markdown
<!-- docs/index.md -->
::: test.MyDataLoader
```
```yaml
# mkdocs.yml
site_name: Test

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://pytorch.org/docs/1.10.1/objects.inv

nav:
  - Home: index.md
```

**System:**
- `mkdocstrings-python` version: 0.7.1
- Python version: 3.9.12
- OS: MacOS
