### ISSUE TITLE
Support for markdown tables inside docstrings

### ISSUE THREAD

**Issue by rudolfbyker** [mkdocstrings/python#38]
**Is your feature request related to a problem? Please describe.**

I can't get this markdown table to render properly when it's part of a function docstring:

```md
    +------------+-----------------+------------+------------------+
    | a          | [b=Table2.rows] | {c=Table3} | [d]              |
    +============+=================+============+==================+
    | 1          | foo             | cols.bar   | Table4.rows.baz  |
    +------------+-----------------+------------+------------------+
    | 2          | moo             | rows.oink  | Table5.cols.bork |
    +------------+-----------------+------------+------------------+
```

It renders like this:

![image](https://user-images.githubusercontent.com/10025342/189082680-af178e4b-b123-4fde-bc06-f59b9b56669e.png)

**Describe the solution you'd like**

Support for the [`tables`](https://python-markdown.github.io/extensions/tables/) markdown extension, even when the table is inside a docstring.

**Describe alternatives you've considered**

- Not using a table in the docstring. Meh.

**Additional context**

`mkdocs.yml`:

```yml
site_name: foo
docs_dir: src
site_dir: dist
theme: material

markdown_extensions:
  - def_list
  - tables
  - toc:
      permalink: true

plugins:
  - search

  - gen-files:
      scripts:
        - gen_pages.py

  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          paths: [../..]
          options:
            docstring_style: google
            show_if_no_docstring: True
            filters: []

  - literate-nav:
      nav_file: nav.md
```

`requirements.txt`:

```
mkdocs~=1.3
mkdocstrings[python]>=0.18
mkdocs-material~=8.4
mkdocs-gen-files~=0.3.5
mkdocs-literate-nav~=0.4.1
```
