### ISSUE TITLE
!include directive fails

### ISSUE THREAD

**Issue by nerdoc** [mkdocstrings/python#47]
In short: I have a repo that includes another one.
```yaml
  - multirepo:
      cleanup: false
      temp_dir: multirepo_imports
      repos:
        - section: 'MedUX common'
          import_url: 'https://gitlab.com/nerdocs/medux/medux-common?branch=development'
```
This works, but I can't do the  navigation of my main repo myself, as `nav` is treated with higher priority as the multirepo `repos` directive.
So I tried the other way:
```yaml
nav:
   - Medux common: "!include https://gitlab.com/nerdocs/medux/medux-common?branch=development"
```

But I only get a 
```
WARNING  -  [13:28:50] "GET /!include%20https:/gitlab.com/nerdocs/medux/medux-common?branch=development
```

**Expected behavior**
I suppose the `!include` directive should work this way.

**System (please complete the following information):**
- mkdocstrings               0.19.0
- mkdocstrings-python        0.8.2
- Python version: 3.10
- OS: Linux
