### ISSUE TITLE
Wrong links for inventory imports

### ISSUE THREAD

**Issue by phil65** [mkdocstrings/python#72]
When adding an inventory file via the config file, the resulting generating links have the url of the inv file prepended.
So in my case I have:

```
plugins:
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            import:
              - url: https://raw.githubusercontent.com/phil65/PrettyQt/master/docs/qt6.inv
                domains: [std, py]
```

but in generated docs, the references link e.g. to https://raw.githubusercontent.com/phil65/PrettyQt/master/docs/https://doc.qt.io/qtforpython/PySide6/QtBluetooth/QBluetoothAddress.html#PySide6.QtBluetooth.PySide6.QtBluetooth.QBluetoothAddress

(see here for example: https://phil65.github.io/PrettyQt/api/bluetooth.html )

Is it a bug or am I missing something?

It would also be nice to be able to use local .inv files, it seems as if this is not possible right now.

Thank you!
