### ISSUE TITLE
`load_external_modules` works not as a global-only option

### ISSUE THREAD

**Issue by monosans** [mkdocstrings/python#87]
**Describe the bug**
[Docs state that `load_external_modules` is a global-only option](https://mkdocstrings.github.io/python/usage/#load_external_modules):

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          load_external_modules: true
```

In fact, it makes effect only when used inside `options` key:

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            load_external_modules: true
```

**System (please complete the following information):**
- `mkdocstrings-python` version: 1.2.0
- Python version: 3.11.3
- OS: Arch Linux
